### ISSUE TITLE
🌈 Bifrost 2023 Roadmap

### ISSUE THREAD

**Issue by JesseXie** [protocol/netops-guild#52]
Description: Root Starmaps issue for Bifrost

Children:
- [ ] https://github.com/protocol/netops/issues/60
- [ ] https://github.com/protocol/netops/issues/61
- [ ] https://github.com/protocol/netops/issues/62
- [ ] https://github.com/protocol/netops/issues/63

Note: This roadmap is subject to change as priorities and circumstances evolve.

Starmap Link: https://starmap.site/roadmap/github.com/protocol/netops/issues/52#simple
